# Generated by Django 4.1.1 on 2023-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_remove_profile_activation_key_and_more'),
        ('accounts', '0015_alter_account_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, max_length=120, null=True, related_name='account_assigned_users', to='common.profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Contact Name'),
        ),
    ]
